ExpressLRS 2.4GHz RX PA RGB ie. Foxeer ELRS 2.4GHz LNA Receiver
FormationFlight/FormationFlight pull request #41
Opened 2023-07-27 18:53 UTC by SilentZen

ExpressLRS 2.4GHz RX PA RGB ie. Foxeer ELRS 2.4GHz LNA Receiver

2023-07-28 20:48 UTC, MUSTARDTIGERFPV commented on targets/expresslrs.ini
> +extends = env:expresslrs_rx_2400_PA_via_UART
```suggestion
extends = env:expresslrs_rx_2400_PA_RGB_via_UART

```

2023-07-28 20:48 UTC, MUSTARDTIGERFPV commented on targets/expresslrs.ini
> +
You can strip these given the latest OTA changes. :)
```suggestion
```

2023-07-28 20:49 UTC, MUSTARDTIGERFPV commented on targets/expresslrs.ini
> +	'-D CFG_TARGET_FULLNAME="ExpressLRS 2.4GHz RX PA RGB"'
```suggestion
	'-D CFG_TARGET_NAME="ELRS2GPARGB"'
	'-D CFG_TARGET_FULLNAME="ExpressLRS 2.4GHz RX PA RGB"'

```

2023-07-28 20:50 UTC, MUSTARDTIGERFPV commented on targets/expresslrs.ini
> +; 2400MHz with PA/LN/RGB (Example: Foxeer ELRS 2.4GHz LNA Receiver)
```suggestion
; 2400MHz with PA/LNA/RGB (Example: Foxeer ELRS 2.4GHz LNA Receiver)

```

2023-07-28 20:54 UTC, MUSTARDTIGERFPV requested changes
Thanks for the PR! If you'd make the minor changes suggested that'd be super helpful - can you also confirm that this PR builds against master and runs successfully on your hardware? :)

2023-07-29 00:11 UTC, MUSTARDTIGERFPV approved these changes

2023-07-29 00:11 UTC, MUSTARDTIGERFPV commented
Thanks so much, @SilentZen! You should come by the FormationFlight Discord btw: https://discord.gg/npaX3VxQjh

2023-08-29 10:36 UTC, SilentZen commented
New to this process, anything more I need to do on this pull request?

2023-08-31 15:16 UTC, MUSTARDTIGERFPV approved these changes

2023-08-31 15:16 UTC, merged

2023-08-31 15:16 UTC, MUSTARDTIGERFPV commented
> New to this process, anything more I need to do on this pull request?

Nope, thanks for the comment to remind me to take a look! :D